=== ardumont/gestioneleves/xsd/cycle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Cycle (constitué de domaines) -->
	<xs:complexType name="CycleType">
		<xs:sequence>
			<xs:element name="domaine" type="DomaineType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<!-- Domaine (constitué de matières) -->
	<xs:complexType name="DomaineType">
		<xs:sequence>
			<xs:element name="matiere" type="MatiereType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<!-- Matiere (constitué de compétences) -->
	<xs:complexType name="MatiereType">
		<xs:sequence>
			<xs:element name="competence" type="CompetenceType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<!-- Competence (constitué de rien du tout) -->
	<xs:complexType name="CompetenceType">
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<!-- Point d'entrée du flux : cycle -->
	<xs:element name="cycle" type="CycleType" />
</xs:schema>

=== ardumont/gestioneleves/xml/import.cycle_domaine_matiere_competence.xml
<?xml version="1.0" encoding="UTF-8"?>
<cycle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cycle.xsd" name="II">
	<domaine name="Instruction civique et morale">
		<matiere name="Instruction civique et morale">
			<competence name="Prendre des responsabilités et être autonome" />
			<competence name="Respecter les adultes et les obéir" />
			<competence name="Respecter les règles de la vie collective" />
			<competence name="Connaître les règles élémentaires de politesse" />
			<competence name="Connaître des règles simples de comportement en société" />
			<competence name="Coopérer à la vie de la classe et rendre service" />
			<competence name="Connaître les principaux symboles de la nation et de la République et les respecter" />
		</matiere>
	</domaine>
	<domaine name="Français">
		<matiere name="Lecture écriture">
			<competence name="Repérer un son auditivement" />
			<competence name="Repérer la graphie d'un son" />
			<competence name="Repérer la graphie d'un son" />
			<competence name="Lire une syllabe" />
			<competence name="Lire un phonème" />
			<competence name="Lire des mots" />
			<competence name="Lire des phrases" />
			<competence name="Lire à haute voix un texte et le comprendre" />
			<competence name="Lire silencieusement une consigne, un texte et les comprendre" />
			<competence name="Connaître le vocabulaire lié à la lecture d'un texte (auteur, éditeur...)" />
			<competence name="Découper un mot en syllabes" />
			<competence name="Découper une phrase en mots" />
			<competence name="Découper un texte en phrases" />
			<competence name="Utiliser des mots d'une même famille" />
			<competence name="Comprendre un texte lu par l'adulte" />
			<competence name="Retrouver, à l'écrit, des informations dans un texte" />
			<competence name="Tenir correctement son outil" />
			<competence name="Ecrire en minuscule de manière sûre et lisible" />
			<competence name="Passer de l'écriture scripte à l'écriture cursive" />
			<competence name="Connaître et savoir écrire les majuscules" />
			<competence name="Ecrire sans faute des mots simples" />
			<competence name="Ecrire sans faute des mots invariables courants" />
			<competence name="Ecrire des syllabes sous la dictée" />
			<competence name="Ecrire des mots sous la dictée" />
			<competence name="Ecrire des phrases sous la dictée" />
			<competence name="Copier une phrase sans faute" />
			<competence name="Copier un court texte sans faute" />
			<competence name="Ordonner des fragments de textes" />
			<competence name="Ecrire la suite d'évènements d'un texte" />
			<competence name="Ecrire spontanément des phrases" />
			<competence name="Ecrire de manière autonome un court texte" />
			<competence name="Relire sa production et la corriger" />
		</matiere>
		<matiere name="Orthographe">
			<competence name="Utiliser la marque du pluriel des noms à l'écrit" />
			<competence name="Utiliser les marques du genre dans le groupe nominal, à l'écrit" />
			<competence name="Utiliser les marques du nombre dans le groupe nominal, à l'écrit" />
			<competence name="Marquer les accords sujet / verbe dans la phrase" />
			<competence name="Passer du singulier au pluriel et inversement dans le groupe nominal" />
			<competence name="Passer du masculin au féminin et inversement dans le groupe nominal" />
			<competence name="Distinguer quelques homonymes grammaticaux" />
			<competence name="Utiliser à l'écrit, les marques du pluriel des verbes" />
		</matiere>
		<matiere name="Grammaire et conjugaison">
			<competence name="Utiliser à l'oral les formes affirmatives, négatives et interrogatives" />
			<competence name="Ordonner les mots d'une phrase" />
			<competence name="Identifier et déplacer les groupes de mots dans la phrase" />
			<competence name="Utiliser le point et la majuscule" />
			<competence name="Distinguer les mots selon leur nature : verbe, nom, adjectif qualificatif, pronoms personnels sujets, articles" />
			<competence name="Trouver le groupe sujet" />
			<competence name="Savoir remplacer le sujet par un pronom personnel" />
			<competence name="Trouver le groupe verbal et le verbe" />
			<competence name="Faire correspondre actions présente, passée, future et le temps de la conjugaison" />
			<competence name="Connaître et utiliser les pronoms de la conjugaison" />
			<competence name="Remplacer le sujet par un pronom personnel" />
			<competence name="Trouver les noms dans la phrase" />
			<competence name="Distinguer nom commun et nom propre" />
			<competence name="Reconnaître et utiliser les adjectifs qualificatifs" />
			<competence name="Reconnaître et utiliser les articles" />
			<competence name="Identifier présent, imparfait, futur, passé composé dans un texte" />
			<competence name="Conjuguer au présent les verbes du 1° groupe" />
			<competence name="Conjuguer au présent le verbe être" />
			<competence name="Conjuguer au présent le verbe avoir" />
			<competence name="Conjuguer au présent le verbe aller" />
			<competence name="Conjuguer au présent le verbe faire" />
			<competence name="Conjuguer au présent le verbe dire" />
			<competence name="Conjuguer au présent le verbe venir" />
			<competence name="Conjuguer au futur les verbes du 1° groupe" />
			<competence name="Conjuguer au futur le verbe être" />
			<competence name="Conjuguer au futur le verbe avoir" />
			<competence name="Conjuguer au passé-composé les verbes du 1° groupe" />
			<competence name="Conjuguer au passé-composé le verbe être" />
			<competence name="Conjuguer au passé-composé le verbe avoir" />
			<competence name="Trouver l'infinitif d'un verbe et son groupe" />
		</matiere>
		<matiere name="Vocabulaire">
			<competence name="Connaître l'ordre alphabétique" />
			<competence name="Utiliser le dictionnaire" />
			<competence name="Distinguer les différents sens d'un mot" />
			<competence name="Distinguer différents homonymes" />
			<competence name="Trouver des synonymes d'un mot" />
			<competence name="Trouver des contraires d'un mot" />
			<competence name="Construire des mots en ajoutant des préfixes" />
			<competence name="Construire des mots en ajoutant des suffixes" />
			<competence name="Distinguer le radical et la terminaison d'un mot" />
			<competence name="Distinguer sens propre et sens figuré" />
			<competence name="Trouver des mots de la même famille" />
		</matiere>
		<matiere name="Langage oral">
			<competence name="S'exprimer clairement à l'oral" />
			<competence name="Savoir écouter les autres" />
			<competence name="Savoir décrire des images" />
			<competence name="Savoir reformuler une formule" />
			<competence name="Savoir présenter à la classe un travail collectif ou individuel" />
			<competence name="Etre capable de dire de mémoire un poême" />
		</matiere>
	</domaine>
	<domaine name="Mathématiques">
		<matiere name="Organisation et gestion des données">
			<competence name="Savoir calculer une augmentation ou d'une diminution" />
			<competence name="Savoir calculer le nombre de parts dans des situations de partage" />
			<competence name="Choisir la bonne opération" />
			<competence name="Savoir repérer les informations utiles" />
			<competence name="Savoir rédiger clairement le résultat" />
		</matiere>
		<matiere name="Nombres">
			<competence name="Savoir dénombrer de 0 à 99" />
			<competence name="Savoir dénombrer de 0 à 999" />
			<competence name="Connaître les doubles et les moitiés des nombres connus" />
			<competence name="Savoir dénombrer en utilisant les groupements par dizaine" />
			<competence name="Savoir dénombrer en utilisant les groupements par centaine" />
			<competence name="Savoir déterminer la valeur d'un chiffre dans l'écriture d'un nombre" />
			<competence name="Savoir décomposer un nombre en écritures additives et multiplicatives" />
			<competence name="Produire des suites orales et écrites de nombres de 2 en 2, 5 en 5" />
			<competence name="Produire des suites orales et écrites de nombres de 10 en 10" />
			<competence name="Produire des suites orales et écrites de nombres de 100 en 100" />
			<competence name="Etre capable de citer le nombre qui suit et celui qui précède" />
			<competence name="Savoir ordonner des nombres en ordre croissant" />
			<competence name="Savoir ordonner des nombres en ordre décroissant" />
			<competence name="Savoir compléter une frise numérique" />
			<competence name="Savoir écrire les nombres en chiffres" />
			<competence name="Savoir écrire les nombres en lettres" />
			<competence name="Savoir comparer et ranger les nombres" />
			<competence name="Savoir encadrer les nombres appris entre deux dizaines" />
			<competence name="Savoir encadrer les nombres appris entre deux centaines" />
			<competence name="Savoir utiliser les signes &lt; &gt; et =" />
			<competence name="Savoir situer des nombres sur une ligne graduée de 1 en 1" />
			<competence name="Savoir situer des nombres sur une ligne graduée de 10 en 10" />
			<competence name="Savoir situer des nombres sur une ligne graduée de 100 en 100" />
		</matiere>
		<matiere name="Calculs">
			<competence name="Construire et utiliser des tables d'addition de 1 à 9" />
			<competence name="Savoir trouver le complément d'un nombre à la dizaine supérieure" />
			<competence name="Connaître le sens de la multiplication" />
			<competence name="Utiliser les tables de multiplication par 2, 3, 4 et 5" />
			<competence name="Savoir multiplier par 10" />
			<competence name="Savoir calculer des additions en ligne" />
			<competence name="Savoir calculer des additions posées en colonne sans retenue" />
			<competence name="Savoir calculer des additions posées en colonne avec retenue" />
			<competence name="Savoir calculer des soustractions en ligne" />
			<competence name="Savoir calculer des soustractions posées en colonne sans retenue" />
			<competence name="Savoir calculer des soustractions posées en colonne avec retenue" />
